### ISSUE TITLE
Indicators like SumN to be compute from beginning of trading day with a backtest of 1 year depth

### ISSUE THREAD

**Issue by remroc** [mementum/backtrader#146] opened 2016-09-08 06:32 UTC
Hello DRo,

I am backtesting a symbol for a 1 year period depth.

I would like to sum the number of occurrences of a event by using the indicators with SumN on a period of 15 bars. I want to make sure the event is working only if it occurs from the beginning of the trading session of the day.

Do you have any recommandation to perform this condition ?

Many thanks,

Remi :)

**Comment by mementum** [comment] 2016-09-09 10:38
There is a filter called `BarReplayer_Open`  (aka `DayStepsFilter`) in the module `backtrader.filters` which breaks a bar in 2 components:

  - `Open` price
  - And then adds the `HLC` components to recreate the full bar

When the `len` of the data changes, you know the incoming price is the `Open` price (actually all 4 fields have the same value) and you can evaluate the `SumN` condition right at the start of the session.

This is a *Replaying* filter and as such you will get 2 `next` calls for each full bar.

**Comment by mementum** [comment] 2016-09-09 14:39
See here for the blog entry regarding this filter: http://www.backtrader.com/posts/2016-07-13-day-in-steps/day-in-steps/

**Comment by remroc** [comment] 2016-09-09 17:15
Hey DRo,

Thanks for this tip. I have not been clear enough.

I am backtesting for 1 year and my data has timeframe = 1 minute. From my understanding, above tip is when you want to split a daily bar to take into account the session open price. As I am in minutes, I don't need to split the day in 2.

Question 1 : **I wonder if it is possible to precise a specific date instead of a period for SumN ?**
Question 2 : **Is it possible to calculate the number of period between to datetimes  ?**

Many thanks for your help.

Cheers,

Remi

**Comment by mementum** [comment] 2016-09-10 22:25
Question 2 is a lot easier to answer

> Question 2 : if no for Question 1, Is it possible to calculate the number bars or the period between to datetimes with bt ?

No. Because the number of bars between two `datetime` points is by no means fixed. In an intraday scenario and with 1 minute bars (for example), some of the 1 minute bars can be missing due to the lack of negotiation.

> Question 1 : I wonder if it is possible to precise a specific date instead of a period for SumN ?

  - If a *specific date* really means a fixed point in time, it wouldn't make any sense because `SumN` would no longer be a *moving* indicator.

  - If by *specific* something like a *time* point or a a backwards *timedelta* is meant, the problem is explained in the answer to *Question 2*: the number of bars is not fixed. That means the code of the indicator would have start scanning bars backwards to find the point in time.

That doesn't mean it cannot be done. The code below should suffice (not tested). It makes a simplification by assuming that with each new day a new session starts (which for most markets is simply true)

```python

import datetime
import backtrader as bt

class SumFromSessionStart(bt.Indicator):
    lines = ('sessionsum',)

    def __init__(self):
        self.lastdt = datetime.datetime.min
        self.lastlen = None  # just a placeholder

    def next(self):
        dt = self.data.datetime.date()
        if dt > self.lastdt:  # new day -> new session
            self.lastdt = dt
            self.lastlen = len(self.data)

        lsum = len(self.data) - self.lastlen + 1  #  +1 covers the 1st bar after a day change
        self.lines.sessionsum[0] = sum(self.data.get(size=lsum)
```

**Comment by remroc** [comment] 2016-09-14 10:27
Thank you DRo. I am trying to work with this tip and will come back to you. Is it possible to have up to 23rd Sept before closing the ticket  ?

**Comment by mementum** [comment] 2016-09-15 07:34
Indeed. Issues are closed due to lack of feedback or inactivity after feedback from this side has been provided, not because they are pointless, in an attempt to keep the number of open issues under control.

In any case, any comment made to an already *closed* issue will still be notified (and acknowledged if needed be)

**Comment by mementum** [comment] 2016-09-29 22:27
Closing it. Should any further feedback be needed, just add a comment to this same ticker. It will be reopened if needed.

**Closed by mementum** 2016-09-29 22:27 UTC
Labels: question

**Comment by remroc** [comment] 2016-09-30 06:23
Still working on it. I will let you know if needed. Thanks DRo
