### ISSUE TITLE
Failed to load CSV which contains null values. 

### ISSUE THREAD

**Issue by xingjianpan** [mementum/backtrader#6] opened 2015-08-03 09:46 UTC
When CSV contains NULL values, below part of the code will generate an error.

https://github.com/mementum/backtrader/blob/master/backtrader/feeds/yahoo.py#L66

**Comment by mementum** [comment] 2015-08-03 09:58
what are "null values"? Can you provide a sample file?

**Comment by xingjianpan** [comment] 2015-08-03 13:26
Using "orcl-1995-2014.txt" as an example.

Orginal values:
Date,Open,High,Low,Close,Volume,Adj Close
1995-01-03,44.12,44.38,42.87,42.87,36301200,2.00
1995-01-04,43.00,43.50,42.37,43.25,46051600,2.01
1995-01-05,43.38,43.50,42.25,42.37,37762800,1.97
1995-01-06,42.37,43.62,41.75,42.87,41864400,2.00
1995-01-09,43.25,44.12,43.13,44.12,34639200,2.05
1995-01-10,44.38,44.88,44.25,44.25,42088000,2.06
1995-01-11,44.62,44.88,42.50,42.94,46762000,2.00
1995-01-12,43.00,43.13,42.25,42.63,41294400,1.98

To reproduce the error I saw, you can randomly remove any volume vlaue. 
(i.e., in below case, i removed the Volume value from second row)
Date,Open,High,Low,Close,Volume,Adj Close
1995-01-03,44.12,44.38,42.87,42.87,36301200,2.00
1995-01-04,43.00,43.50,42.37,43.25,,2.01
1995-01-05,43.38,43.50,42.25,42.37,37762800,1.97
1995-01-06,42.37,43.62,41.75,42.87,41864400,2.00
1995-01-09,43.25,44.12,43.13,44.12,34639200,2.05
1995-01-10,44.38,44.88,44.25,44.25,42088000,2.06
1995-01-11,44.62,44.88,42.50,42.94,46762000,2.00
1995-01-12,43.00,43.13,42.25,42.63,41294400,1.98
1995-01-13,43.13,43.44,42.00,42.13,55039200,1.96

And the if i run the example given in the tutorial, I would get below errors. 

```shell

Starting Portfolio Value: 10000.00
Traceback (most recent call last):
  File "sample2.py", line 149, in <module>
    cerebro.run()
  File "d:\Users\Xingjian Pan\Anaconda\lib\site-packages\backtrader\cerebro.py", line 126, in run
    runstrat = self.runstrategies(iterstrat)
  File "d:\Users\Xingjian Pan\Anaconda\lib\site-packages\backtrader\cerebro.py", line 146, in runstrategies
    data.preload()
  File "d:\Users\Xingjian Pan\Anaconda\lib\site-packages\backtrader\feed.py", line 142, in preload
    while self.load():
  File "d:\Users\Xingjian Pan\Anaconda\lib\site-packages\backtrader\feed.py", line 151, in load
    if not self._load():
  File "d:\Users\Xingjian Pan\Anaconda\lib\site-packages\backtrader\feed.py", line 249, in _load
    return self._loadline(linetokens)
  File "d:\Users\Xingjian Pan\Anaconda\lib\site-packages\backtrader\feeds\yahoo.py", line 71, in _loadline
    self.lines.volume[0] = float(linetokens[next(i)])
ValueError: could not convert string to float:
```


It's very common for the source(i.e, financial databases) to contain NULL values, and those NULL values will reflect as blank in the csv file. 

Hope this clarifies, please let me know if you need further information.

Thanks,
Xingjian

**Comment by mementum** [comment] 2015-08-03 13:51
The question remains as to whether the feed that was being loaded for the triggering of the error for this issue was a Yahoo CSV feed and not a tampered with version

**Comment by xingjianpan** [comment] 2015-08-03 14:05
Hi @mementum ,

Thanks for the reply. If I understand you correctly, you are saying this issue was caused by Yahoo CSV feed, which is not in scope of backtrader.  

In that case, it might be helpful to 1) make the error message more informative buy printing out the incorrect values, or 2) indicate in the tutorial that the CSV file  to be feed to backtrader is expected to have values for each fields (open, high, low, volume, close, adj close) and cannot be blank. 

Also,  do you have any suggestions  on 1) load data into backtrader from a database? 2)load data into backtrader from a pandas dataframe? Currently I will  convert souce into a csv file first and load the file using Yahoo CSV feed. 

Thanks,
Xingjian

**Comment by mementum** [comment] 2015-08-03 14:15
The Yahoo CSV feed is in the scope ... it's the class supporting those
feeds the one generating the error.

To document the issue you propose to tamper with one of the existing
provided sample files which is obviously out of scope.

And the issue is: "what has actually produced the error?"

Reading your answer it seems clear you are converting existing data and
hoping it will be magically loaded by code which is intended to work with
Yahoo downloaded data, which creates the error.

Pandas support can be a thing to tackle and I can look into it.

**Comment by mementum** [comment] 2015-08-03 23:23
A GenericCSVData data feed class has been added. It's not extensively tested but the tests I run show the basics are at least working.

It has been committed and pushed.

See usage at: http://www.backtrader.com/posts/2015-08-04/generic-csv-datafeed/

**Comment by xingjianpan** [comment] 2015-08-04 03:24
Hi @mementum,

Many thanks for looking into this!



I tested GenericCSVData, it works as expected  with python2, however I got below error on python3.4.1.

```python
import backtrader.feeds as btfeed

data = btfeed.GenericCSVData(
    dataname='datas/yahoo/orcl-1995-2014.txt',

    fromdate=datetime.datetime(2000, 1, 1),
    todate=datetime.datetime(2000, 12, 31),

    nullvalue=0.0,

    dtformat=('%Y-%m-%d'),

    datetime=0,
    open=1,
    high=2,
    low=3,
    close=4,
    volume=5,
    openinterest=-1
)
```


```shell
Starting Portfolio Value: 10000.00
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-20d4235530e5> in <module>()
     18 
     19 # Run over everything
---> 20 cerebro.run()
     21 
     22 # Print out the final result

C:\Users\u8010137\AppData\Local\Continuum\Anaconda3\lib\site-packages\backtrader-1.1.0.88-py3.4.egg\backtrader\cerebro.py in run(self, **kwargs)
    138             # let's skip process "spawning"
    139             for iterstrat in iterstrats:
--> 140                 runstrat = self.runstrategies(iterstrat)
    141                 self.runstrats.append(runstrat)
    142         else:

C:\Users\u8010137\AppData\Local\Continuum\Anaconda3\lib\site-packages\backtrader-1.1.0.88-py3.4.egg\backtrader\cerebro.py in runstrategies(self, iterstrat)
    158             data.start()
    159             if self.params.preload:
--> 160                 data.preload()
    161 
    162         for stratcls, sargs, skwargs in iterstrat:

C:\Users\u8010137\AppData\Local\Continuum\Anaconda3\lib\site-packages\backtrader-1.1.0.88-py3.4.egg\backtrader\feed.py in preload(self)
    140 
    141     def preload(self):
--> 142         while self.load():
    143             pass
    144 

C:\Users\u8010137\AppData\Local\Continuum\Anaconda3\lib\site-packages\backtrader-1.1.0.88-py3.4.egg\backtrader\feed.py in load(self)
    149             # move data pointer forward for new bar
    150             self.forward()
--> 151             if not self._load():
    152                 # no bar - undo data pointer
    153                 self.backwards()

C:\Users\u8010137\AppData\Local\Continuum\Anaconda3\lib\site-packages\backtrader-1.1.0.88-py3.4.egg\backtrader\feed.py in _load(self)
    247         line = line.rstrip(six.b('\r\n'))
    248         linetokens = line.split(six.b(self.p.separator))
--> 249         return self._loadline(linetokens)
    250 
    251 

C:\Users\u8010137\AppData\Local\Continuum\Anaconda3\lib\site-packages\backtrader-1.1.0.88-py3.4.egg\backtrader\feeds\csvgeneric.py in _loadline(self, linetokens)
     59             dtformat += 'T' + self.p.tmformat
     60 
---> 61         dt = datetime.datetime.strptime(dtfield, dtformat)
     62         self.lines.datetime[0] = date2num(dt)
     63 

TypeError: must be str, not bytes
```

**Comment by mementum** [comment] 2015-08-04 08:27
In any case ... much more important than the code traceback when it comes down to input that produces an error ... is providing "input" which produces the error.

Best regards

**Closed** 2015-08-04 21:25 UTC
Labels: enhancement

**Comment by xingjianpan** [comment] 2015-08-05 02:49
Hi @mementum , 

Many thanks for the fix!  Btw, the input data is sample data (orcl-1995-2014.txt).

**Comment by femtotrader** [comment] 2015-08-05 17:44
Using Blaze (and odo) https://github.com/mementum/backtrader/issues/10 you could also have this generic CSV data source but also much more.

see http://blaze.pydata.org/en/latest/uri.html

Here is a way to iterate (by chunk) over a very large table (or CSV file)

    from odo import odo, chunks
    table_uri = 'dialect+driver://user:password@host:port/database::table'
    for i, chunk in enumerate(odo(table_uri, chunks(pd.DataFrame), chunksize=chunksize)):
        print("="*5 + " chunk %d " % (i + 1) + "="*5)
        for j, row in chunk.iterrows():
            print(row)

**Comment by mementum** [comment] 2015-08-05 21:45
To complete the issue I have added a post (and also documentation) on how to develop any kind of CSV data feed.

http://www.backtrader.com/posts/2015-08-06/csv-data-feed-development/
