### ISSUE TITLE
error 518 on ibtest.py

### ISSUE THREAD

**Issue by r-kalma** [mementum/backtrader#164] opened 2016-10-12 10:13 UTC
Hi,

I played around with the software and actually made a backtest strategy functional which I now want to paper trade on IB. It was a steep learning curve to get where I am today, but thanks for this library, its awesome. The steps for migrating from backtest to live are still a bit vague to me. I found the ibtest.py so I thought, lets get this running first so I can see if the connection to my demo IB is ok.

I ran into this issue:

~~~~
python ibtest.py --port 7496 --data0 AAPL-STK-SMART-USD
Server Version: 76
TWS Time at connection:20161012 11:56:25 CET
--------------------------------------------------
Strategy Created
--------------------------------------------------
Datetime, Open, High, Low, Close, Volume, OpenInterest, SMA
***** STORE NOTIF: <error id=-1, errorCode=518, errorMsg=Request Contract Data Sending Error - 'int' object has no attribute 'encode'>
***** STORE NOTIF: Ambiguous contract: none/multiple answers received
***** DATA NOTIF: DISCONNECTED
~~~~

I guess there is a problem with the ticker name being ambiguous, but I really can't figure out why, because its the same as you use in some examples. I tried other ones but they all produce the same error.
Any ideas?

Thanks in advance,

**Comment by r-kalma** [comment] 2016-10-13 12:13
OK its seems I'm not subscribed to that datafeed. But I am subscribed to IDEAL FX (IDEAL PRO) 
So I tried the following:
~~~~
ibtest.py --port 7496 --data0 EUR.USD-CASH-IDEALPRO
Server Version: 76
TWS Time at connection:20161013 14:06:06 CET
--------------------------------------------------
Strategy Created
--------------------------------------------------
Datetime, Open, High, Low, Close, Volume, OpenInterest, SMA
***** STORE NOTIF: <error id=-1, errorCode=518, errorMsg=Request Contract Data Sending Error - 'int' object has no attribute 'encode'>
***** STORE NOTIF: Ambiguous contract: none/multiple answers received
***** DATA NOTIF: DISCONNECTED
~~~~

Now I tried the to get up running in ibpy directly and it gives me:
~~~~
Server Version: 76
TWS Time at connection:20161013 14:00:32 CET
<managedAccounts accountsList=DU516314>
<nextValidId orderId=1>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfuture>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:eufarm>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:cashfarm>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfarm.us>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfarm>
<error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:ilhmds>
<error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:euhmds>
<error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:ushmds>
<error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:fundfarm>
Contract Values:EUR,CASH,IDEALPRO,USD,,0.0,:
* * * * REQUESTING MARKET DATA * * * *
EUR:: bid: 1.1038
EUR:: ask: 1.10381
<tickGeneric tickerId=1, tickType=49, value=0.0>
<tickGeneric tickerId=1, tickType=49, value=0.0>
EUR:: bid: 1.10378
EUR:: ask: 1.10379
~~~~
Could it be that this response line: `<managedAccounts accountsList=DU516314>` is giving problems, as I don't see that returned in your example.

Thanks.

**Comment by mementum** [comment] 2016-10-14 02:30
The `<managedAccounts accountsList=DU516314>` is managed internally actually as the start point to identify a working account.

You can try to execute `ibtest` with `--debug` and all messages received from `TWS` will be printed to `stdout`. That would be helpful.

**Comment by mementum** [comment] 2016-10-14 02:38
In any case the *not being subscribed* distracted me and failed to see that your `518` is actually caused by this:

  - `Request Contract Data Sending Error - 'int' object has no attribute 'encode'`

This has obviously nothing to do with being subscribed or not. The easiest educated guess is:

  - Are you using Python 3.x? (because of the `encode` hint in the error message)

**Comment by mementum** [comment] 2016-10-14 03:23
It would seem that the offending line in `ibpy` is in `ib/lib/__init__.py`:

```python
class DataOutputStream(object):
    """ Partial implementation of the Java DataOutputStream type

    """
    def __init__(self, stream):
        """ Constructor.

        @param stream any object with send method
        """
        self.send = stream.send

    def write(self, data, pack=struct.pack, eol=struct.pack('!b', 0)):
        """ Writes data to the contained stream.

        @param data string to send, or 0
        @return None
        """
        send = self.send
        if data == 0:
            send(eol)
        else:
            for char in data:
                if sys.version_info[0] > 2:
                    char = char.encode('utf-8')
                send(pack('!c', char))
```

This is the only `encode` in `ibpy`. But before getting here `ibpy` transforms everything into a *string* with the *overloaded* `send` methods.

One of the *sends* is apparently failing during `reqContractDetails` and an exception is captured and flagged with error code `518`.

**Comment by r-kalma** [comment] 2016-10-14 08:33
I'm using python 3.5.2. Not sure if that is an issue, but I switched to 2.7 and tested it again. Now it outputs:
~~~~
python ibtest.py --port 7496 --data0 EUR.USD-CASH-IDEALPRO
Server Version: 76
TWS Time at connection:20161014 10:22:52 CET
--------------------------------------------------
Strategy Created
--------------------------------------------------
Timezone from ContractDetails: EST5EDT
Datetime, Open, High, Low, Close, Volume, OpenInterest, SMA
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:hfarm>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:jfarm>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfuture>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:eufarm>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:cashfarm>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfarm.us>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfarm>
***** STORE NOTIF: <error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:ilhmds>
***** STORE NOTIF: <error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:euhmds>
***** STORE NOTIF: <error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:ushmds>
***** STORE NOTIF: <error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:fundfarm>
***** DATA NOTIF: DELAYED
***** DATA NOTIF: DISCONNECTED
~~~~

And with --debug
~~~~
python ibtest.py --port 7496 --data0 EUR.USD-CASH-IDEALPRO --debug
Server Version: 76
TWS Time at connection:20161014 10:31:06 CET
<managedAccounts accountsList=DU516314>
<nextValidId orderId=1>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:hfarm>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:jfarm>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfuture>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:eufarm>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:cashfarm>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfarm.us>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfarm>
<error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:ilhmds>
<error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:euhmds>
<error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:ushmds>
<error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:fundfarm>
<contractDetails reqId=16777216, contractDetails=<ib.ext.ContractDetails.ContractDetails object at 0x7fd05fa078d0>>
<contractDetailsEnd reqId=16777216>
<currentTime time=1476433866>
--------------------------------------------------
Strategy Created
--------------------------------------------------
Timezone from ContractDetails: EST5EDT
Datetime, Open, High, Low, Close, Volume, OpenInterest, SMA
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:hfarm>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:jfarm>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfuture>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:eufarm>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:cashfarm>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfarm.us>
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfarm>
***** STORE NOTIF: <error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:ilhmds>
***** STORE NOTIF: <error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:euhmds>
***** STORE NOTIF: <error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:ushmds>
***** STORE NOTIF: <error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:fundfarm>
***** DATA NOTIF: DELAYED
<tickPrice tickerId=16777217, field=1, price=1.10139, canAutoExecute=1>
<tickSize tickerId=16777217, field=0, size=1000000>
<tickPrice tickerId=16777217, field=2, price=1.1014, canAutoExecute=1>
<tickSize tickerId=16777217, field=3, size=4180000>
<tickSize tickerId=16777217, field=0, size=1000000>
<tickSize tickerId=16777217, field=3, size=4180000>
<tickSize tickerId=16777217, field=5, size=0>
<tickPrice tickerId=16777217, field=6, price=1.10585, canAutoExecute=0>
<tickPrice tickerId=16777217, field=7, price=1.10045, canAutoExecute=0>
<tickPrice tickerId=16777217, field=9, price=1.1057, canAutoExecute=0>
<tickGeneric tickerId=16777217, tickType=49, value=0.0>
***** DATA NOTIF: DISCONNECTED
~~~~

**Comment by mementum** [comment] 2016-10-14 09:17
That shows it is a `Python 3.x` issue. My educated guess it is that this down to `ibpy`, but it is only an educated guess. It seems some not all of the values in the `Contract` object are converted to a `str` under Python 3.x during a `reqContractDetails`

Run the sample with `--resample` and then parameters of your choice for `timeframe` and `compression`. For example:
```
python ibtest.py --port 7496 --data0 EUR.USD-CASH-IDEALPRO --resample --timeframe Seconds --compression 5
```

This should keep the sample running.

**Comment by r-kalma** [comment] 2016-10-14 10:48
That works!

` Timeframe: Minutes` and `Compression: 2` gives me:
~~~~
......
Data0, 1049, 736251.436111, 2016-10-14T06:28:00.000000, 1.10143, 1.10148, 1.1012, 1.10122, -1.0, 0, 1.101324
Data0, 1050, 736251.4375, 2016-10-14T06:30:00.000000, 1.10122, 1.10144, 1.1012, 1.1014, -1.0, 0, 1.101326
Data0, 1051, 736251.438889, 2016-10-14T06:32:00.000000, 1.1014, 1.10158, 1.10128, 1.10155, -1.0, 0, 1.101368
Data0, 1052, 736251.440278, 2016-10-14T06:34:00.000000, 1.10155, 1.10178, 1.10147, 1.10178, -1.0, 0, 1.101476
***** DATA NOTIF: LIVE
Data0, 1053, 736251.441667, 2016-10-14T06:36:00.000000, 1.10162, 1.10174, 1.10162, 1.10169, 0.0, 0, 1.101528
Data0, 1054, 736251.443056, 2016-10-14T06:38:00.000000, 1.10171, 1.10192, 1.10167, 1.10177, 0.0, 0, 1.101638
Data0, 1055, 736251.444444, 2016-10-14T06:40:00.000000, 1.10174, 1.10198, 1.1016, 1.10167, 0.0, 0, 1.101692
~~~~

I will run this in python 2.7 for the time being.

Thanks a lot for helping me out.

**Comment by mementum** [comment] 2016-10-15 08:47
The development branch already contains a fix for this for Python 3. `IbPy` was not covering all cases of overloading in send and will not convert `bytes`. Rather than changing `IbPy`, things are directly sent as `str` to `IbPy`

**Comment by r-kalma** [comment] 2016-10-16 07:47
Great!

**Closed** 2016-10-16 18:47 UTC
Labels: question

**Comment by mementum** [comment] 2016-10-16 19:02
In release 1.9.8.99
