### ISSUE TITLE
example (Quickstart-Optimize) does not work

### ISSUE THREAD

**Issue by grinboy** [mementum/backtrader#133] opened 2016-08-29 08:19 UTC
```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import datetime  # For datetime objects
import os.path  # To manage paths
import sys  # To find out the script name (in argv[0])


# Import the backtrader platform
import backtrader as bt


# Create a Stratey
class TestStrategy(bt.Strategy):
    params = (
        ('maperiod', 15),
        ('printlog', False),
    )

    def log(self, txt, dt=None, doprint=False):
        ''' Logging function fot this strategy'''
        if self.params.printlog or doprint:
            dt = dt or self.datas[0].datetime.date(0)
            print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self):
        # Keep a reference to the "close" line in the data[0] dataseries
        self.dataclose = self.datas[0].close

        # To keep track of pending orders and buy price/commission
        self.order = None
        self.buyprice = None
        self.buycomm = None

        # Add a MovingAverageSimple indicator
        self.sma = bt.indicators.SimpleMovingAverage(
            self.datas[0], period=self.params.maperiod)

    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            # Buy/Sell order submitted/accepted to/by broker - Nothing to do
            return

        # Check if an order has been completed
        # Attention: broker could reject order if not enougth cash
        if order.status in [order.Completed, order.Canceled, order.Margin]:
            if order.isbuy():
                self.log(
                    'BUY EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                    (order.executed.price,
                     order.executed.value,
                     order.executed.comm))

                self.buyprice = order.executed.price
                self.buycomm = order.executed.comm
            else:  # Sell
                self.log('SELL EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                         (order.executed.price,
                          order.executed.value,
                          order.executed.comm))

            self.bar_executed = len(self)

        # Write down: no pending order
        self.order = None

    def notify_trade(self, trade):
        if not trade.isclosed:
            return

        self.log('OPERATION PROFIT, GROSS %.2f, NET %.2f' %
                 (trade.pnl, trade.pnlcomm))

    def next(self):
        # Simply log the closing price of the series from the reference
        self.log('Close, %.2f' % self.dataclose[0])

        # Check if an order is pending ... if yes, we cannot send a 2nd one
        if self.order:
            return

        # Check if we are in the market
        if not self.position:

            # Not yet ... we MIGHT BUY if ...
            if self.dataclose[0] > self.sma[0]:

                # BUY, BUY, BUY!!! (with all possible default parameters)
                self.log('BUY CREATE, %.2f' % self.dataclose[0])

                # Keep track of the created order to avoid a 2nd order
                self.order = self.buy()

        else:

            if self.dataclose[0] < self.sma[0]:
                # SELL, SELL, SELL!!! (with all possible default parameters)
                self.log('SELL CREATE, %.2f' % self.dataclose[0])

                # Keep track of the created order to avoid a 2nd order
                self.order = self.sell()

    def stop(self):
        self.log('(MA Period %2d) Ending Value %.2f' %
                 (self.params.maperiod, self.broker.getvalue()), doprint=True)
        

if __name__ == '__main__':
    
    cerebro=bt.Cerebro()
    
    strats = cerebro.optstrategy(TestStrategy,maperiod=range(10, 12))
    
    cerebro.addstrategy(TestStrategy)
    cerebro.broker.setcommission(0.001)

    
    modpath = "D:\\python\\"
    datapath = os.path.join(modpath, 'datas/orcl-1995-2014.txt')

    # Create a Data Feed
    data = bt.feeds.YahooFinanceCSVData(
        dataname=datapath,
        # Do not pass values before this date
        fromdate=datetime.datetime(2000, 1, 1),
        # Do not pass values after this date
        todate=datetime.datetime(2000, 12, 31),
        reverse=False)
    
    cerebro.adddata(data)
    
    cerebro.broker.set_cash(10000.00)
    cerebro.addsizer(bt.sizers.FixedSize, stake=10)
    cerebro.broker.setcommission(commission=0.0)
    
    cerebro.run()
```
    
Copied example, I launched and does not work

```
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]

runfile('D:/Downloads/WinPython-64bit-3.4.4.2/notebooks/back_trader.py', wdir='D:/Downloads/WinPython-64bit-3.4.4.2/notebooks')
Exception in thread Thread-8:
Traceback (most recent call last):
  File "D:\Downloads\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\threading.py", line 911, in _bootstrap_inner
    self.run()
  File "D:\Downloads\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Downloads\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\multiprocessing\pool.py", line 429, in _handle_results
    task = get()
  File "D:\Downloads\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\multiprocessing\connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'TestStrategy' on <module '__main__' (<_frozen_importlib.SourceFileLoader object at 0x0000000002298240>)>
```

**Comment by mementum** [comment] 2016-08-29 09:37
Duplicate of #118.

Optimization works like a charm. The same cannot be said from *Notebooks/Spyder* (and especially under Windows) when coupled with the `multiprocessing` module, due to how these consoles start the *python* *kernel* (and also *freeze* it) and use for interactivity.

**Closed by mementum** 2016-08-29 09:37 UTC
